### ISSUE TITLE
Unhelpful Error Message Connecting Seq to Vec of different size

### ISSUE THREAD

**Issue by jackkoenig** [freechipsproject/chisel3#482]
The following:

```scala
class VecErrorTop extends Module {
  val io = IO(new Bundle {
    val out = Output(Vec(4, UInt(32.W)))
  })

  io.out <> Seq.tabulate(5)(i => i.U)
}
```

Gives the error:
```
[error] (run-main-6) java.lang.IllegalArgumentException: requirement failed
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:212)
        at chisel3.core.Vec.$less$greater(Aggregate.scala:170)
        at VecErrorTop.<init>(VecBulkConnectError.scala:12)
        at VecErrorDriver$$anonfun$2.apply(VecBulkConnectError.scala:16)
        at VecErrorDriver$$anonfun$2.apply(VecBulkConnectError.scala:16)
```

**Comment by ducky64** [comment]
This should just give a Chisel error message.
