### ISSUE TITLE
problem with chisel3 using centos

### ISSUE THREAD

**Issue by esolera** [freechipsproject/chisel3#707]
when a run "make" comand in a chisel3 repository a get this error:

    [warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
    [warn] 
    [warn]  * xml-apis:xml-apis:1.3.04 is selected over 2.0.2
    [warn]      +- org.apache.xmlgraphics:batik-script:1.8            (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-anim:1.8              (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-transcoder:1.8        (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-bridge:1.8            (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-svg-dom:1.8           (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-parser:1.8            (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-dom:1.8               (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-css:1.8               (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-ext:1.8               (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-extension:1.8         (depends on 1.3.04)
    [warn]      +- org.apache.xmlgraphics:batik-svggen:1.8            (depends on 1.3.04)
    [warn]      +- xalan:xalan:2.7.0                                  (depends on 2.0.2)
    [warn] 
    [warn] Run 'evicted' to see detailed eviction warnings
    usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...
     java.util.NoSuchElementException: head of empty stream
        at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1028)
        at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1026)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:138)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:122)
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        
        at sbt . EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp 
        (INode.scala:69)

        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        [error] java.util.NoSuchElementException: head of empty stream
        [error] Use 'last' for the full log.
       SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
       SLF4J: Defaulting to no-operation (NOP) logger implementation
        SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
       Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by colinschmidt** [comment]
Fixed in other issue
