### ISSUE TITLE
Vec.fill  INPUT OUTPUT

### ISSUE THREAD

**Issue by xubaqian** [freechipsproject/chisel3#807]
There is a simple matrix transformation file from rocc-template
```
import Chisel._
import scala.collection.mutable.HashMap
import scala.collection.mutable.ArrayBuffer

class ThetaModule(val W: Int = 64) extends Module {
  val io = new Bundle {
    val state_i = Vec.fill(5*5){Bits(INPUT, width = W)}
    val state_o = Vec.fill(5*5){Bits(OUTPUT,width = W)}
  }

  val bc = Vec.fill(5){Bits(width = W)}
  for(i <- 0 until 5) {
    bc(i) := io.state_i(i*5+0) ^ io.state_i(i*5+1) ^ io.state_i(i*5+2) ^ io.state_i(i*5+3) ^ io.state_i(i*5+4)
  }

  for(i <- 0 until 5) {
    val t = Bits(width = W)
    t := bc((i+4)%5) ^ common.ROTL(bc((i+1)%5), UInt(1), UInt(W))
    for(j <- 0 until 5) {
      io.state_o(i*5+j) := io.state_i(i*5+j) ^ t
    }
  }
}
```

When I instantiate it using `val theta = Module(new ThetaModule(64))`, I got the following error message
```
Caused by: chisel3.core.Binding$BindingException: 'other' (chisel3.core.UInt@37ce3)Error: iodef.state_o(*): Already bound to WireBinding(rocket.ThetaModule@37b72)
	at chisel3.core.Binding$.checkSynthesizable(Binding.scala:185)
	at chisel3.core.Bits.binop(Bits.scala:160)
	at chisel3.core.UInt.do_$up(Bits.scala:455)
	at rocket.ThetaModule$$anonfun$2$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(theta.scala:29)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at rocket.ThetaModule$$anonfun$2.apply$mcVI$sp(theta.scala:28)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	at rocket.ThetaModule.<init>(theta.scala:25)
```
It seems errors result from `Vec.fill` and this line  `io.state_o(i*5+j) := io.state_i(i*5+j) ^ t`

**Comment by jackkoenig** [comment]
`Vec.fill` constructs literal wires rather than just types. In this case, you want `Vec(size, type)`. Try:
```scala
  val io = new Bundle {
    val state_i = Vec(5*5, Bits(INPUT, width = W))
    val state_o = Vec(5*5, Bits(OUTPUT,width = W))
  }
```
