### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by Aliishaa** [freechipsproject/chisel3#865]
Here is the code:

         
    import chisel3._
    import chisel3.util._

    class Compare1 extends Module {
    val io = IO(new Bundle {
    val in1 = Input(Vec(5, UInt(3.W)))
    val in2 = Input(Vec(5, UInt(3.W)))
    val out = Output(Vec(6, UInt(3.W)))

     })

    for (k <- 0 until 5){
    
	when (io.in4(k) === io.in3(k + 1)) {
        io.out(k) := io.in1(k) 
        }
     }

       io.out(5) := io.in2(4) 

    }
 
### Error :

     java.lang.IndexOutOfBoundsException: 5
	at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:132)
	at scala.collection.immutable.Vector.apply(Vector.scala:122)
	at chisel3.core.Vec.apply(Aggregate.scala:232)
	at problems.Compare1$$anonfun$1$$anonfun$apply$2.apply(Compare1.scala:27)
	at problems.Compare1$$anonfun$1$$anonfun$apply$2.apply(Compare1.scala:27)
	at chisel3.core.WhenContext$$anonfun$1.apply(When.scala:72)
	at chisel3.core.WhenContext$$anonfun$1.apply(When.scala:72)
	at scala.Option.foreach(Option.scala:257)
	at chisel3.core.WhenContext.<init>(When.scala:72)
	at chisel3.core.when$.apply(When.scala:32)
	at problems.Compare1$$anonfun$1.apply(Compare1.scala:27)
	at problems.Compare1$$anonfun$1.apply(Compare1.scala:25)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at problems.Compare1.<init>(Compare1.scala:25)
	at problems.Launcher$$anonfun$4$$anonfun$apply$7.apply(Launcher.scala:25)
	at problems.Launcher$$anonfun$4$$anonfun$apply$7.apply(Launcher.scala:25)
	at chisel3.core.Module$.do_apply(Module.scala:49)
	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
	at chisel3.Driver$$anonfun$elaborate$1.apply(Driver.scala:93)
	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:297)
	at chisel3.internal.Builder$$anonfun$build$1.apply(Builder.scala:295)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at chisel3.internal.Builder$.build(Builder.scala:295)
	at chisel3.Driver$.elaborate(Driver.scala:93)
	at chisel3.Driver$.execute(Driver.scala:140)
	at chisel3.iotesters.setupFirrtlTerpBackend$.apply(FirrtlTerpBackend.scala:130)
	at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply$mcZ$sp(Driver.scala:52)
	at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply(Driver.scala:39)
	at chisel3.iotesters.Driver$$anonfun$execute$1$$anonfun$apply$mcZ$sp$1.apply(Driver.scala:39)
	at logger.Logger$$anonfun$makeScope$1.apply(Logger.scala:129)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at logger.Logger$.makeScope(Logger.scala:127)
	at chisel3.iotesters.Driver$$anonfun$execute$1.apply$mcZ$sp(Driver.scala:39)
	at chisel3.iotesters.Driver$$anonfun$execute$1.apply(Driver.scala:39)
	at chisel3.iotesters.Driver$$anonfun$execute$1.apply(Driver.scala:39)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at chisel3.iotesters.Driver$.execute(Driver.scala:38)
	at problems.Launcher$$anonfun$4.apply(Launcher.scala:25)
	at problems.Launcher$$anonfun$4.apply(Launcher.scala:24)
	at utils.TutorialRunner$$anonfun$apply$2.apply(TutorialRunner.scala:42)
	at utils.TutorialRunner$$anonfun$apply$2.apply(TutorialRunner.scala:35)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at utils.TutorialRunner$.apply(TutorialRunner.scala:35)
	at problems.Launcher$.main(Launcher.scala:184)
	at problems.Launcher.main(Launcher.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:93)
	at sbt.Run.run0(Run.scala:87)
	at sbt.Run.execute$1(Run.scala:65)
	at sbt.Run.$anonfun$run$3(Run.scala:69)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at sbt.Run.directExecute$1(Run.scala:69)
	at sbt.Run.run(Run.scala:78)
	at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1147)
	at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1142)
	at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
    ================================================================================
    Errors: 1: in the following tutorials
    Tutorial Compare1: exception 5
      ================================================================================

Can somebody help?

**Comment by edwardcwang** [comment]
There doesn't appear to be any `io.in4` or `io.in3` in your code... they are probably smaller than size 6 (since `k + 1` gives you an index of 5).
